spring:
  application:
    name: tlias-web-management
  datasource:
    url: jdbc:mysql://192.168.100.128:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 744180
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-ai-zhangxiru
    region: cn-beijing

